# Use an official Python runtime as a parent image
FROM python:2.7-slim

MAINTAINER Aaditya Agrawal

RUN apt-get update && apt-get install postgresql postgresql-contrib

# Create Directory
RUN mkdir /flask_blog

# Set the working directory to /flask_blog
WORKDIR /flask_blog

# Copy the current directory contents into the container at /app
ADD . /flask_blog


# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt
RUN pip install -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 5000

# Define environment variable
ENV NAME World

# Run run.py when the container launches
CMD ["python", "run.py"]